apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.label_val }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.deploy_name }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ .Values.label_val }}
  type: NodePort
status:
  loadBalancer: {}
